const translations = {
  PL: {
    togetherToTheGoal: 'Razem do celu!',
    hematorun: 'HEMATOBIEG',
    foundationForHelpingPeopleWithLeukemia:
      'Fundacji Na Rzecz Pomocy Chorym Na Białaczki',
    processingInformation: 'INFORMACJA O PRZETWARZANIU DANYCH OSOBOWYCH',
    processingInformationDetails:
      'INFORMACJA O PRZETWARZANIU DANYCH OSOBOWYCH- FUNDACJA NA RZECZ POMOCY CHORYM NA BIAŁACZKI (dalej “Fundacja”), we współpracy z firmami zewnętrznymi organizuje I BIEG CHARYTATYWNY. Impreza odbywać się będzie stacjonarnie, w dniu 12 maja 2024 r. W toku imprezy będzie istniała możliwość robienia zdjęć Gości, Uczestników oraz w szczególności Zwycięzców, w sposób umożliwiający ich identyfikację. Zdjęcia następnie mogą zostać wykorzystane dla potrzeb prowadzonych wewnętrznych i zewnętrznych działań komunikacyjnych i marketingowych. Na podstawie art. 6 ust. 1 lit. a RODO, przetwarzanie przez Fundację wizerunku Gości, Uczestników oraz w szczególności Zwycięsców dla opisanych celów wymaga wyrażenia zgody przez osoby fizyczne, których dane są przetwarzane.',
    foundationInformationClause: 'KLAUZULA INFORMACYJNA FUNDACJI',
    foundationInformationClauseDetails:
      'Na podstawie art. 13 Rozporządzenia Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (ogólne rozporządzenie o ochronie danych), dalej RODO, poniżej zamieszczamy informacje dotyczące przetwarzania danych osobowych w postaci wizerunku Gości, Uczestników oraz w szczególności Zwycięzców podczas Biegu przez Fundację dalej ADO: Administratorem Danych Osobowych jest FUNDACJA NA RZECZ POMOCY CHORYM NA BIAŁACZKI . z siedzibą w Łodzi, przy ul. Pabianickiej 62, 93-513 Łódź, KRS 0000069531, e-mail: kontakt@fundacja.hematologiczna.org  ADO przetwarza dane osobowe dla celów prowadzonych zewnętrznych i wewnętrznych działań komunikacyjnych i marketingowych (Art. 6 ust. 1 lit. a RODO), Odbiorcami danych osobowych może być firma zewnętrzna współorganizująca Bieg oraz inne firmy, które na zlecenie Fundacji będą przygotowywały materiały dla celów komunikacyjnych i marketingowych. ADO nie przekazuje danych osobowych poza Europejski Obszar Gospodarczy. Dane osobowe przechwytywane będą przez okres niezbędny dla celów prowadzonych wewnętrznych i zewnętrznych działań komunikacyjnych i marketingowych. Osoba której dane są przetwarzane ma prawo dostępu do swoich danych oraz otrzymania ich kopii, prawo do sprostowania (poprawiania) swoich danych, prawo do ograniczenia przetwarzania, prawo do bycia zapomnianym, prawo do sprzeciwu, prawo do przenoszenia danych, prawo do cofnięcia udzielonej zgody w każdym czasie, prawo do wniesienia skargi do Urzędu Ochrony Danych Osobowych. Podanie danych osobowych w zakresie objętym klauzulą jest całkowicie dobrowolne. W ramach działalności ADO nie dochodzi do zautomatyzowanego podejmowania decyzji, w tym profilowania, z wykorzystaniem zebranych danych osobowych.',
    button: 'Rozumiem',
  },
  EN: {
    togetherToTheGoal: 'Together to the goal!',
    hematorun: 'HEMATORUN',
    foundationForHelpingPeopleWithLeukemia:
      'Foundation for Helping People with Leukemia',
    processingInformation: 'PERSONAL DATA PROCESSING INFORMATION',
    processingInformationDetails:
      'PERSONAL DATA PROCESSING INFORMATION - THE FOUNDATION FOR THE BENEFIT OF LEUKEMIA PATIENTS (hereinafter referred to as the "Foundation"), in cooperation with external companies, is organizing the 1ST CHARITY RUN. The event will take place in person on May 12, 2024. During the event, there will be an opportunity to take photos of Guests, Participants, and particularly Winners, in a way that allows their identification. The photos may then be used for the purposes of internal and external communication and marketing activities. Pursuant to Article 6(1)(a) of the GDPR, the processing of the image of Guests, Participants, and particularly Winners for the described purposes requires the consent of the individuals whose data are being processed.',
    foundationInformationClause: 'FOUNDATION INFORMATION CLAUSE',
    foundationInformationClauseDetails:
      'Pursuant to Article 13 of Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (General Data Protection Regulation), hereinafter referred to as the GDPR, below we provide information regarding the processing of personal data in the form of the image of Guests, Participants, and particularly Winners during the Run by the Foundation hereinafter referred to as the Data Controller: The Personal Data Administrator is THE FOUNDATION FOR THE BENEFIT OF LEUKEMIA PATIENTS, with its registered office in Łódź, at 62 Pabianicka Street, 93-513 Łódź, NIP (Tax Identification Number) 0000069531, email: kontakt@fundacja.hematologiczna.org. The Data Controller processes personal data for the purposes of external and internal communication and marketing activities (Art. 6(1)(a) of the GDPR). The recipients of personal data may be an external company co-organizing the Run and other companies that, at the request of the Foundation, will prepare materials for communication and marketing purposes. The Data Controller does not transfer personal data outside the European Economic Area. Personal data will be retained for the period necessary for the purposes of internal and external communication and marketing activities. The person whose data are processed has the right to access their data and receive a copy thereof, the right to rectify (correct) their data, the right to restrict processing, the right to erasure, the right to object, the right to data portability, the right to withdraw consent at any time, and the right to lodge a complaint with the Office for Personal Data Protection. Providing personal data within the scope covered by the clause is entirely voluntary. Within the Data Controllers activities, there is no automated decision-making, including profiling, based on the collected personal data.',
    button: 'I understand',
  },
};

export default translations;
